/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_firstapp_hakan_cameraapp_Mushroom */

#ifndef _Included_com_firstapp_hakan_cameraapp_Mushroom
#define _Included_com_firstapp_hakan_cameraapp_Mushroom
#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     com_firstapp_hakan_cameraapp_Mushroom
 * Method:    detectMushroom
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_firstapp_hakan_cameraapp_Mushroom_detectMushroom
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
