# Generated by CMake 3.6.0-rc2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget libcharset libiconv)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target libcharset
add_library(libcharset SHARED IMPORTED)

# Create imported target libiconv
add_library(libiconv SHARED IMPORTED)

set_target_properties(libiconv PROPERTIES
  INTERFACE_LINK_LIBRARIES "libcharset"
)

# Import target "libcharset" for configuration "Debug"
set_property(TARGET libcharset APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libcharset PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Users/Hakan/Desktop/Mushroom-Identifier/Android/CameraApp/app/build/intermediates/cmake/debug/obj/armeabi-v7a/liblibcharset.so"
  IMPORTED_SONAME_DEBUG "liblibcharset.so"
  )

# Import target "libiconv" for configuration "Debug"
set_property(TARGET libiconv APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libiconv PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Users/Hakan/Desktop/Mushroom-Identifier/Android/CameraApp/app/build/intermediates/cmake/debug/obj/armeabi-v7a/liblibiconv.so"
  IMPORTED_SONAME_DEBUG "liblibiconv.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
